const fs = require('fs');
const path = require('path');

const base = path.join('C:\\Claude Cowork\\Projects\\ai autonomy\\src');

/*
 * EDITING MODEL (see PROJECT-PLAN.md section 2):
 *   - This generator OWNS the structural shell of a gap page, but ONLY while the
 *     page is still a pristine scaffold (its <div class="content"> still contains
 *     the string "content-placeholder").
 *   - Once a page has hand-written content, the guard below makes this script
 *     REFUSE to overwrite it, so re-running can never silently destroy authored work.
 *   - To deliberately re-scaffold an authored page (e.g. a sitewide <head> change):
 *         node generate-pages.js --force
 *     That writes a timestamped .bak of the existing file first; you must then
 *     MANUALLY re-merge your <div class="content"> from the .bak into the result.
 *     Never run --force without doing the re-merge.
 */
const FORCE = process.argv.includes('--force');

const gaps = [
  { module: 1, modTitle: 'From Text to Numbers', id: 'G11', slug: 'g11-tokenization', title: 'Tokenization &amp; Embedding Spaces', oneLiner: 'Text enters the model as tokens mapped to high-dimensional vectors where geometric distance encodes semantic similarity.', analogy: 'A postal system that converts addresses into GPS coordinates &mdash; text becomes math where distance = meaning.', why: "The learner&#39;s &quot;next-word guesser&quot; frame assumes the model works on words. It works on tokens embedded in a space where meaning has geometric structure.", argue: "After this page, you can explain why an LLM doesn&#39;t work on &quot;words&quot; at all &mdash; and why its mathematical representation of meaning is the first crack in the &quot;guesser&quot; frame.", readTime: '~10 min', prereqs: [], questions: ['Why does the model split &quot;unhappiness&quot; into sub-word tokens rather than treating it as one word?', 'What does it mean that &quot;king &minus; man + woman &asymp; queen&quot; in embedding space?', 'Why is the embedding space a better representation than a dictionary lookup?'] },
  { module: 1, modTitle: 'From Text to Numbers', id: 'G1', slug: 'g01-weights', title: 'What Weights Actually Encode', oneLiner: 'LLM weights are a compressed statistical world model encoding concepts, relationships, and reasoning patterns &mdash; not a lookup table.', analogy: 'A compressed river-physics map, not a list of rivers &mdash; the weights encode how language works, not individual facts.', why: "Once the learner sees that weights encode structure, the &quot;next-word guesser&quot; frame collapses.", argue: "After this page, you can tell a skeptic: &quot;The model doesn&#39;t store facts &mdash; it stores the physics of how language encodes meaning.&quot;", readTime: '~12 min', prereqs: [{id:'G11',title:'Tokenization &amp; Embedding Spaces',slug:'g11-tokenization',mod:1}], questions: ['What is the difference between a lookup table and a compressed statistical model?', 'Can you explain why &quot;Paris is the capital of France&quot; lives in model weights without being stored as a fact?', 'What happens to a weight-encoded concept when you ask the model a question it has never seen?'] },
  { module: 1, modTitle: 'From Text to Numbers', id: 'G12', slug: 'g12-training-objective', title: 'The Training Objective', oneLiner: 'Predicting the next token forces the model to learn grammar, facts, reasoning patterns, world knowledge, and theory of mind.', analogy: 'Learning cricket by predicting the next ball &mdash; to predict well, you must learn physics, player psychology, pitch conditions, and game strategy.', why: "The direct rebuttal to &quot;it just guesses the next word.&quot; To guess well, it must learn everything humans encode in language.", argue: "After this page, you can turn the skeptic&#39;s own argument: &quot;Yes, it predicts the next word &mdash; and to do that well, it had to learn everything.&quot;", readTime: '~8 min', prereqs: [{id:'G11',title:'Tokenization &amp; Embedding Spaces',slug:'g11-tokenization',mod:1},{id:'G1',title:'What Weights Actually Encode',slug:'g01-weights',mod:1}], questions: ['Why does next-token prediction require the model to learn factual knowledge, not just grammar?', 'What is self-supervised learning, and why does it scale better than supervised learning?', 'Give an example of a sentence where predicting the next word requires reasoning, not pattern matching.'] },
  { module: 2, modTitle: 'The Learning Engine', id: 'G13', slug: 'g13-backpropagation', title: 'Backpropagation &amp; Gradient Descent', oneLiner: 'The model improves by computing prediction error and propagating it backward to nudge each weight toward reducing future errors.', analogy: 'A consultant getting client feedback after each engagement and adjusting their approach &mdash; trillions of small adjustments improving each prediction.', why: "Intelligence is the cumulative result of trillions of small weight adjustments, each one reducing prediction error by a tiny amount.", argue: "After this page, you can explain the mechanism: &quot;Intelligence wasn&#39;t programmed &mdash; it was learned through trillions of tiny corrections.&quot;", readTime: '~12 min', prereqs: [{id:'G1',title:'What Weights Actually Encode',slug:'g01-weights',mod:1},{id:'G12',title:'The Training Objective',slug:'g12-training-objective',mod:1}], questions: ['What is a loss function and what does it measure?', 'In plain language, what does &quot;propagate the error backward&quot; mean?', 'Why does a model trained on next-token prediction end up encoding world knowledge rather than just word co-occurrence statistics?'] },
  { module: 2, modTitle: 'The Learning Engine', id: 'G4', slug: 'g04-scaling-laws', title: 'Neural Scaling Laws', oneLiner: 'Model capability scales predictably with size, data, and compute &mdash; a measurable empirical law, not magic.', analogy: 'Water cooling from 20&deg;C to 0&deg;C: mostly smooth change, then a phase transition into ice &mdash; a qualitatively new thing.', why: "Scaling laws are the empirical answer to &quot;where did the intelligence come from?&quot; &mdash; more scale leads to qualitatively different capabilities.", argue: "After this page, you can cite the empirical law: &quot;Intelligence scales predictably with compute &mdash; and at certain scales, qualitatively new abilities appear.&quot;", readTime: '~10 min', prereqs: [{id:'G13',title:'Backpropagation &amp; Gradient Descent',slug:'g13-backpropagation',mod:2}], questions: ['What is the basic form of a neural scaling law?', 'Why does a 70B-parameter model do things a 7B model cannot?', 'Can you predict from scaling laws whether a new capability will emerge?'] },
  { module: 2, modTitle: 'The Learning Engine', id: 'G14', slug: 'g14-pretraining-data', title: 'Pre-Training Data', oneLiner: 'The composition, quality, and diversity of pre-training data directly determine what the model learns &mdash; data is the curriculum.', analogy: "A medical student&#39;s curriculum: the breadth and quality of cases they study determines what kind of doctor they become.", why: "Intelligence comes from architecture AND data. A transformer trained only on restaurant reviews would never learn physics.", argue: "After this page, you can explain why data diversity matters: &quot;The model&#39;s intelligence is shaped by what it studied &mdash; data is the curriculum.&quot;", readTime: '~8 min', prereqs: [{id:'G13',title:'Backpropagation &amp; Gradient Descent',slug:'g13-backpropagation',mod:2},{id:'G4',title:'Neural Scaling Laws',slug:'g04-scaling-laws',mod:2}], questions: ['Why would a model trained on 10x more data from a single domain perform worse than one trained on diverse data?', 'What is &quot;data contamination&quot; and why does it matter for evaluating model intelligence?', 'How does the Chinchilla finding change how we think about the data-compute tradeoff?'] },
  { module: 2, modTitle: 'The Learning Engine', id: 'G5', slug: 'g05-emergence', title: 'Emergent Capabilities', oneLiner: 'At certain scales, LLMs appear to develop qualitatively new abilities &mdash; though whether these transitions are truly discontinuous or artifacts of measurement is actively debated.', analogy: 'An ant colony: no individual ant knows the architecture, but at scale the colony builds a temperature-regulated structure.', why: "The core empirical answer to &quot;where did the intelligence come from?&quot; &mdash; it was not programmed; it emerged from scale.", argue: "After this page, you have the killer answer: &quot;Nobody programmed it to reason &mdash; the ability emerged at scale, the way ice forms when water cools past a threshold.&quot;", readTime: '~12 min', prereqs: [{id:'G4',title:'Neural Scaling Laws',slug:'g04-scaling-laws',mod:2}], questions: ['What is the difference between a capability that scales smoothly and one that emerges discontinuously?', 'Name two capabilities that were emergent.', 'Why does emergence matter to the &quot;next-word guesser&quot; debate?'] },
  { module: 2, modTitle: 'The Learning Engine', id: 'G15', slug: 'g15-fine-tuning', title: 'Fine-Tuning &amp; Transfer Learning', oneLiner: "A pre-trained model&#39;s knowledge transfers to new tasks with minimal additional training &mdash; general intelligence specializes.", analogy: 'A general-practice lawyer who specializes in tax law &mdash; same foundational training, narrowed by focused additional experience.', why: "Understanding transfer learning explains why a model trained on general text can become a code assistant or medical advisor.", argue: "After this page, you can explain how a single model becomes many specialists &mdash; and why that&#39;s transfer of genuine understanding, not separate programs.", readTime: '~10 min', prereqs: [{id:'G14',title:'Pre-Training Data',slug:'g14-pretraining-data',mod:2},{id:'G1',title:'What Weights Actually Encode',slug:'g01-weights',mod:1}], questions: ['What is the difference between pre-training and fine-tuning?', 'Why can fine-tuning on 10,000 examples change model behavior when pre-training used trillions of tokens?', 'What is catastrophic forgetting, and how does it constrain fine-tuning?'] },
  { module: 3, modTitle: 'The Reasoning Machine', id: 'G2', slug: 'g02-attention', title: 'Transformer Attention', oneLiner: 'Self-attention is a learned mechanism for routing information between tokens based on relevance &mdash; structured relational reasoning, not autocomplete.', analogy: 'A Supreme Court panel where each justice highlights different relationships in the same document, then combines verdicts.', why: "If attention = structured relational reasoning, the model is not a statistical autocomplete machine.", argue: "After this page, you can dismantle &quot;autocomplete&quot;: &quot;The model doesn&#39;t just look at the last few words &mdash; it tracks relationships across the entire context, selectively.&quot;", readTime: '~15 min', prereqs: [{id:'G1',title:'What Weights Actually Encode',slug:'g01-weights',mod:1},{id:'G11',title:'Tokenization &amp; Embedding Spaces',slug:'g11-tokenization',mod:1}], questions: ['What does a single attention head &quot;do&quot; in plain language?', 'Why can a model trained on &quot;predict next word&quot; learn to track who said what in a dialogue?', 'How is attention different from just counting word co-occurrences?'] },
  { module: 3, modTitle: 'The Reasoning Machine', id: 'G3', slug: 'g03-in-context-learning', title: 'In-Context Learning', oneLiner: 'LLMs adapt their behavior from examples in the prompt without any training &mdash; runtime reasoning, not memorization retrieval.', analogy: "An experienced consultant who reads your company&#39;s memo format from three examples and immediately produces a fourth.", why: "Directly answers &quot;how will the AI know what lens to apply?&quot; &mdash; the lens is in the prompt context; the model reasons from it.", argue: "After this page, you can demonstrate a capability no lookup table has: &quot;Give it three examples of a task it&#39;s never seen &mdash; it learns the pattern on the spot, no retraining.&quot;", readTime: '~12 min', prereqs: [{id:'G1',title:'What Weights Actually Encode',slug:'g01-weights',mod:1},{id:'G2',title:'Transformer Attention',slug:'g02-attention',mod:3}], questions: ['Why can an LLM solve a task format it has never seen, given three examples?', 'How is ICL different from fine-tuning?', 'How would you use ICL to tell a research agent which lens to apply?'] },
  { module: 3, modTitle: 'The Reasoning Machine', id: 'G6', slug: 'g06-compositional-generalization', title: 'Compositional Generalization', oneLiner: 'LLMs combine learned sub-patterns to handle situations never literally seen &mdash; genuine problem-solving, not retrieval.', analogy: 'A jazz musician who improvises by recombining learned harmonic patterns, not a jukebox that only plays stored songs.', why: "Answers &quot;if it just guesses the next word, how does it solve novel problems?&quot; &mdash; compositional generalization is the mechanistic answer.", argue: "After this page, you can answer the hardest skeptic question: &quot;It solves novel problems by recombining learned patterns &mdash; the way a jazz musician improvises.&quot;", readTime: '~12 min', prereqs: [{id:'G2',title:'Transformer Attention',slug:'g02-attention',mod:3},{id:'G3',title:'In-Context Learning',slug:'g03-in-context-learning',mod:3}], questions: ['What is the difference between retrieving a memorized answer and composing a new one from parts?', 'How would an LLM answer a question about a country it has never seen?', 'Where does compositional generalization break down?'] },
  { module: 3, modTitle: 'The Reasoning Machine', id: 'G33', slug: 'g33-hallucination', title: 'Hallucination', oneLiner: 'LLMs sometimes generate confident, fluent, entirely false statements &mdash; a failure mode with multiple proposed causes including training data gaps, calibration failures, and decoding dynamics.', analogy: "A brilliant consultant who, when they don&#39;t know the answer, confidently improvises something plausible rather than saying &quot;I don&#39;t know.&quot;", why: "The strongest honest counterweight. Understanding hallucination makes the learner&#39;s intelligence claims defensible, not naive.", argue: "After this page, your intelligence claims are honest: &quot;Yes, it&#39;s genuinely intelligent &mdash; AND it has systematic failure modes a truly understanding mind wouldn&#39;t have.&quot;", readTime: '~12 min', prereqs: [{id:'G6',title:'Compositional Generalization',slug:'g06-compositional-generalization',mod:3},{id:'G1',title:'What Weights Actually Encode',slug:'g01-weights',mod:1}], questions: ['Why does a model that &quot;knows&quot; Paris is the capital of France sometimes say it&#39;s Lyon?', 'What is the difference between a hallucination and a reasoning error?', 'What does hallucination tell us about whether LLMs &quot;understand&quot; what they say?'] },
  { module: 3, modTitle: 'The Reasoning Machine', id: 'G9', slug: 'g09-chain-of-thought', title: 'Chain-of-Thought as Computation', oneLiner: 'CoT prompting forces multi-step computation in the visible token stream, measurably improving accuracy &mdash; a mechanism, not decoration.', analogy: "A mathematician&#39;s scratchpad &mdash; the intermediate steps are not decoration; they are the computation.", why: "Understanding CoT as a computational mechanism changes how you design prompts and evaluate agent reasoning traces.", argue: "After this page, you can explain why &quot;think step by step&quot; works: &quot;The intermediate tokens ARE the computation &mdash; the model literally reasons through them.&quot;", readTime: '~10 min', prereqs: [{id:'G2',title:'Transformer Attention',slug:'g02-attention',mod:3},{id:'G3',title:'In-Context Learning',slug:'g03-in-context-learning',mod:3}], questions: ['Why does adding &quot;think step by step&quot; improve accuracy on math problems?', 'What is the computational mechanism behind CoT?', 'When does CoT fail, and why?'] },
  { module: 3, modTitle: 'The Reasoning Machine', id: 'G16', slug: 'g16-advanced-reasoning', title: 'Advanced Reasoning', oneLiner: 'Beyond linear CoT: tree-of-thought (search), reflection (metacognition), and self-correction (error repair) &mdash; three distinct reasoning strategies.', analogy: 'A chess grandmaster who considers multiple lines of play, evaluates positions, and backtracks from bad lines.', why: "Understanding these architectures lets you design agents that explore, evaluate, and backtrack &mdash; not just think linearly.", argue: "After this page, you can describe three distinct ways LLMs reason beyond simple linear thinking &mdash; search, self-evaluation, and error repair.", readTime: '~12 min', prereqs: [{id:'G9',title:'Chain-of-Thought as Computation',slug:'g09-chain-of-thought',mod:3},{id:'G6',title:'Compositional Generalization',slug:'g06-compositional-generalization',mod:3}], questions: ['What is the difference between chain-of-thought and tree-of-thought reasoning?', 'When is reflection genuinely useful vs. when does it just add latency?', 'How would you implement a self-correction loop without infinite recursion?'] },
  { module: 3, modTitle: 'The Reasoning Machine', id: 'G17', slug: 'g17-extended-thinking', title: 'Extended Thinking', oneLiner: 'Modern LLMs use dedicated thinking token budgets for internal reasoning &mdash; turning single-pass prediction into deliberate reasoning with variable compute.', analogy: "Answering &quot;2+2&quot; instantly vs. spending ten minutes on a differential equation &mdash; intelligence means allocating more effort to harder problems.", why: "The strongest evidence against the &quot;next-word guesser&quot; frame. Variable compute allocation is a hallmark of intelligence.", argue: "After this page, you have the definitive argument: &quot;A next-word guesser uses the same effort on every word. This model spends MORE time on harder problems &mdash; that&#39;s intelligence.&quot;", readTime: '~10 min', prereqs: [{id:'G9',title:'Chain-of-Thought as Computation',slug:'g09-chain-of-thought',mod:3},{id:'G16',title:'Advanced Reasoning',slug:'g16-advanced-reasoning',mod:3}], questions: ['What is the difference between fixed and variable compute per token?', 'Why does variable compute allocation matter for intelligence claims?', 'How does extended thinking relate to System 1 / System 2 dual-process cognition?'] },
  { module: 3, modTitle: 'The Reasoning Machine', id: 'G29', slug: 'g29-multimodal', title: 'Multimodal Intelligence', oneLiner: 'Modern LLMs process images, audio, and text in a unified representation space &mdash; genuine cross-modal reasoning, not just captioning.', analogy: 'A doctor who reads the X-ray, listens to the patient, and checks lab results &mdash; intelligence that reasons across different types of information.', why: "Multimodal reasoning demonstrates that &quot;next-token prediction&quot; generalizes beyond text into a qualitatively richer form of intelligence.", argue: "After this page, you can point out that the model reasons across images and text simultaneously &mdash; no &quot;next-word guesser&quot; does that.", readTime: '~10 min', prereqs: [{id:'G2',title:'Transformer Attention',slug:'g02-attention',mod:3},{id:'G11',title:'Tokenization &amp; Embedding Spaces',slug:'g11-tokenization',mod:1}], questions: ['How does a vision-language model represent an image in the same space as text?', 'What is the difference between image captioning and cross-modal reasoning?', 'Give an example of a task requiring genuine multimodal reasoning.'] },
  { module: 4, modTitle: 'The Alignment Layer', id: 'G18', slug: 'g18-rlhf', title: 'RLHF Deep Dive', oneLiner: 'RLHF trains a reward model on human preferences, then uses it to fine-tune the LLM &mdash; translating human judgment into mathematical optimization.', analogy: "Training a new employee by showing pairs of draft emails and asking &quot;which one would you send?&quot; &mdash; they learn your judgment without a rulebook.", why: "The mechanics of how &quot;be helpful, be honest, be harmless&quot; gets translated from human judgment into model behavior.", argue: "After this page, you can explain how human values get into the machine &mdash; not through rules, but through preference learning.", readTime: '~12 min', prereqs: [{id:'G15',title:'Fine-Tuning &amp; Transfer Learning',slug:'g15-fine-tuning',mod:2},{id:'G13',title:'Backpropagation &amp; Gradient Descent',slug:'g13-backpropagation',mod:2}], questions: ['What is a reward model and how is it trained?', 'Why does RLHF produce behavior that supervised fine-tuning alone cannot?', 'What is the KL penalty in RLHF and why is it necessary?'] },
  { module: 4, modTitle: 'The Alignment Layer', id: 'G19', slug: 'g19-beyond-rlhf', title: 'Beyond RLHF', oneLiner: 'DPO eliminates the separate reward model. Constitutional AI has the model critique and revise its own outputs against principles.', analogy: 'The employee who can now critique their own drafts against company principles before you review them &mdash; self-supervised quality control.', why: "Claude uses constitutional AI. Understanding CAI explains why Claude behaves differently from GPT.", argue: "After this page, you can explain why Claude is different: &quot;It doesn&#39;t just learn from human feedback &mdash; it critiques its own outputs against explicit principles.&quot;", readTime: '~10 min', prereqs: [{id:'G18',title:'RLHF Deep Dive',slug:'g18-rlhf',mod:4}], questions: ['What problem does DPO solve that RLHF has?', 'How does Constitutional AI work &mdash; the critique and revision steps?', 'Why might self-supervised alignment scale better than human-feedback-only?'] },
  { module: 4, modTitle: 'The Alignment Layer', id: 'G20', slug: 'g20-alignment', title: 'The Alignment Problem', oneLiner: 'An intelligent system that cannot be directed toward human-intended goals is not useful intelligence &mdash; alignment ensures capability serves intent.', analogy: 'A brilliant but literal-minded intern: they optimize exactly what you told them, even if what you told them is not what you meant.', why: "An unaligned autonomous agent is the canonical AI safety failure mode. This transforms how you design system prompts.", argue: "After this page, you understand the core safety challenge: &quot;Intelligence without alignment optimizes the wrong thing &mdash; and the smarter it is, the worse that gets.&quot;", readTime: '~12 min', prereqs: [{id:'G18',title:'RLHF Deep Dive',slug:'g18-rlhf',mod:4},{id:'G5',title:'Emergent Capabilities',slug:'g05-emergence',mod:2}], questions: ['What is the difference between capability and alignment?', 'What is reward hacking?', 'In your own agent work, what is one concrete way misalignment could manifest?'] },
  { module: 4, modTitle: 'The Alignment Layer', id: 'G21', slug: 'g21-adversarial', title: 'Adversarial Robustness', oneLiner: 'LLMs can be manipulated through adversarial prompts that bypass safety training &mdash; understanding attacks is essential for building robust agents.', analogy: 'Social engineering attacks on a company &mdash; the security system works until someone tricks the employee into bypassing it.', why: "Every user input to your agent is a potential adversarial prompt. Understanding the attack surface is essential.", argue: "After this page, you can design agents that handle untrusted input safely &mdash; because you understand how safety training gets bypassed.", readTime: '~10 min', prereqs: [{id:'G20',title:'The Alignment Problem',slug:'g20-alignment',mod:4},{id:'G3',title:'In-Context Learning',slug:'g03-in-context-learning',mod:3}], questions: ['What is a jailbreak and why do they work despite alignment training?', 'What is red-teaming and how does it differ from unit testing?', 'Name two defense strategies for agent systems processing untrusted input.'] },
  { module: 5, modTitle: 'The Agent Architecture', id: 'G8', slug: 'g08-lens-picking', title: 'How the Agent Picks the Right Lens', oneLiner: "The agent selects its approach because system prompt, few-shot examples, or retrieved context provides decision criteria &mdash; in-context reasoning applies them.", analogy: 'An expert panel moderator who applies your stated review criteria to novel research without needing domain pre-training.', why: "The concrete connection between ICL, attention, and the observe-reason-act loop in your own agent-building work.", argue: "After this page, you can design system prompts that reliably steer agent behavior &mdash; and verify the agent is actually applying the lens you intended.", readTime: '~10 min', prereqs: [{id:'G3',title:'In-Context Learning',slug:'g03-in-context-learning',mod:3},{id:'G2',title:'Transformer Attention',slug:'g02-attention',mod:3}], questions: ['Write a system prompt that tells a research agent to apply a &quot;critical&quot; vs. &quot;exploratory&quot; lens.', 'How would you verify the agent is applying the right lens?', 'What would cause the agent to apply the wrong lens?'] },
  { module: 5, modTitle: 'The Agent Architecture', id: 'G22', slug: 'g22-memory-architectures', title: 'Memory Architectures', oneLiner: 'RAG and vector databases give agents long-term memory by retrieving relevant information at inference time and injecting it into the prompt.', analogy: "A consultant who keeps organized case files and retrieves the relevant one before each engagement &mdash; not relying on what&#39;s in their head.", why: "Your agents need to work with information exceeding the context window. RAG bridges reasoning capability and the world&#39;s knowledge.", argue: "After this page, you can explain how agents access knowledge beyond their training &mdash; and why RAG is not just &quot;copy-paste from a database.&quot;", readTime: '~12 min', prereqs: [{id:'G3',title:'In-Context Learning',slug:'g03-in-context-learning',mod:3},{id:'G11',title:'Tokenization &amp; Embedding Spaces',slug:'g11-tokenization',mod:1}], questions: ['What is retrieval-augmented generation and how does it extend the context window?', 'How does semantic search differ from keyword search?', 'What failure modes does RAG introduce that a base LLM does not have?'] },
  { module: 5, modTitle: 'The Agent Architecture', id: 'G23', slug: 'g23-goal-decomposition', title: 'Goal Decomposition', oneLiner: 'Autonomous agents break complex goals into sub-tasks, sequence them by dependency, and execute iteratively &mdash; separating chatbot from agent.', analogy: "A project manager breaking &quot;launch the product&quot; into workstreams, milestones, and tasks &mdash; each actionable, each with dependencies.", why: "Understanding goal decomposition as a formal capability lets you design agents that handle genuinely complex, multi-phase tasks.", argue: "After this page, you can articulate what separates an agent from a chatbot: &quot;An agent doesn&#39;t just answer &mdash; it plans, decomposes, and executes.&quot;", readTime: '~10 min', prereqs: [{id:'G8',title:'How the Agent Picks the Right Lens',slug:'g08-lens-picking',mod:5},{id:'G16',title:'Advanced Reasoning',slug:'g16-advanced-reasoning',mod:3}], questions: ['What is the difference between a flat task list and hierarchical goal decomposition?', 'How does an agent decide sub-task order with dependencies?', 'What happens when a sub-task fails &mdash; how should an agent recover?'] },
  { module: 5, modTitle: 'The Agent Architecture', id: 'G24', slug: 'g24-multi-agent', title: 'Multi-Agent Systems', oneLiner: 'Multiple LLM agents can collaborate, debate, specialize, and coordinate &mdash; producing collective behavior exceeding any single agent.', analogy: 'A McKinsey engagement team: partner, engagement manager, three associates &mdash; each specializes, they coordinate, team output exceeds any individual.', why: "Understanding multi-agent dynamics lets you design agent teams that genuinely collaborate rather than just run in parallel.", argue: "After this page, you can design agent teams where the whole exceeds the parts &mdash; and explain why that&#39;s emergent collective intelligence.", readTime: '~10 min', prereqs: [{id:'G23',title:'Goal Decomposition',slug:'g23-goal-decomposition',mod:5},{id:'G8',title:'How the Agent Picks the Right Lens',slug:'g08-lens-picking',mod:5}], questions: ['What is the difference between agents in parallel and agents collaborating?', 'How does a &quot;debate&quot; pattern improve answer quality?', 'What coordination overhead do multi-agent systems introduce?'] },
  { module: 5, modTitle: 'The Agent Architecture', id: 'G25', slug: 'g25-autonomy-spectrum', title: 'The Autonomy Spectrum', oneLiner: 'Agent autonomy is a spectrum from fully human-controlled to fully autonomous, with meaningful engineering tradeoffs at each level.', analogy: 'Self-driving car levels (L0&ndash;L5): each trades control for independence, with real engineering consequences at each transition.', why: "This project is about autonomy. This gap gives the formal vocabulary for choosing where each agent should operate on the spectrum.", argue: "After this page, you can make informed decisions about how much autonomy to give each agent &mdash; and explain why &quot;more autonomy&quot; isn&#39;t always better.", readTime: '~10 min', prereqs: [{id:'G23',title:'Goal Decomposition',slug:'g23-goal-decomposition',mod:5},{id:'G20',title:'The Alignment Problem',slug:'g20-alignment',mod:4}], questions: ['Name three distinct levels on the autonomy spectrum with examples.', 'What factors determine where an agent should sit?', 'Why is the alignment problem more severe at higher autonomy levels?'] },
  { module: 6, modTitle: 'Seeing Inside', id: 'G26', slug: 'g26-mechanistic-interpretability', title: 'Mechanistic Interpretability', oneLiner: 'Researchers can identify specific circuits inside transformer weights performing identifiable computations &mdash; causal understanding of internal mechanisms.', analogy: "An electrical engineer reverse-engineering a circuit board by tracing connections &mdash; not just measuring what the board does, but understanding why.", why: "Answers &quot;how do you know what it&#39;s actually doing inside?&quot; &mdash; empirical tools for causal understanding of internal mechanisms.", argue: "After this page, you can counter &quot;it&#39;s a black box&quot;: &quot;We can trace specific circuits performing specific computations &mdash; it&#39;s not opaque anymore.&quot;", readTime: '~12 min', prereqs: [{id:'G1',title:'What Weights Actually Encode',slug:'g01-weights',mod:1},{id:'G2',title:'Transformer Attention',slug:'g02-attention',mod:3}], questions: ['What is an induction head and what computation does it perform?', 'How does mechanistic interpretability differ from probing classifiers?', 'What did Olsson et al. 2022 discover about in-context learning circuits?'] },
  { module: 6, modTitle: 'Seeing Inside', id: 'G27', slug: 'g27-superposition', title: 'Superposition &amp; Polysemanticity', oneLiner: 'Models represent far more concepts than dimensions via superposition &mdash; mathematically principled compression, not random noise.', analogy: 'A library fitting 100,000 books on 10,000 shelves by encoding each book as a combination of shelf positions.', why: "Answers &quot;how can a finite model know so much?&quot; &mdash; mathematical compression stores more knowledge than the architecture seemingly allows.", argue: "After this page, you can explain the compression trick: &quot;The model stores more concepts than it has dimensions &mdash; using the same math that compresses music files.&quot;", readTime: '~12 min', prereqs: [{id:'G1',title:'What Weights Actually Encode',slug:'g01-weights',mod:1},{id:'G26',title:'Mechanistic Interpretability',slug:'g26-mechanistic-interpretability',mod:6}], questions: ['What is superposition in neural networks?', 'Why might a single neuron activate for both &quot;cat&quot; and &quot;car&quot; &mdash; and why is this not a bug?', 'If a model has 10,000 dimensions but represents 100,000 concepts, what does that tell you?'] },
  { module: 6, modTitle: 'Seeing Inside', id: 'G34', slug: 'g34-world-models', title: 'Internal World Models', oneLiner: 'LLMs trained only on sequences build internal representations of the underlying world state &mdash; board positions, spatial relationships, truth &mdash; despite never being shown that world.', analogy: "A chess commentator who has only heard move annotations read aloud &mdash; never seen a board &mdash; yet builds a remarkably accurate mental picture of the position.", why: "The single most powerful empirical rebuttal of the &quot;next-word guesser&quot; frame. The model was never shown the world; it inferred it.", argue: "After this page, you have the strongest empirical evidence: &quot;A model trained only on move sequences built an internal chessboard. No guesser does that.&quot;", readTime: '~12 min', prereqs: [{id:'G26',title:'Mechanistic Interpretability',slug:'g26-mechanistic-interpretability',mod:6},{id:'G1',title:'What Weights Actually Encode',slug:'g01-weights',mod:1}], questions: ['What did the Othello-GPT experiment show about internal representations?', 'Why is it significant that the model was never shown a board &mdash; only move sequences?', 'How do linear probes reveal internal representations vs. create them?'] },
  { module: 6, modTitle: 'Seeing Inside', id: 'G28', slug: 'g28-benchmarking', title: 'Benchmarking Intelligence', oneLiner: 'LLM intelligence is measured through benchmarks, but benchmarks can be gamed, contaminated, or wrong &mdash; evaluation methodology is essential.', analogy: "A student who scores 95% from memorizing the answer key vs. one who scores 85% from understanding &mdash; the score alone doesn&#39;t tell you which.", why: "Understanding benchmarking lets you distinguish &quot;scores 90% on MMLU&quot; from &quot;genuinely better at reasoning.&quot;", argue: "After this page, you can critically evaluate AI claims: &quot;Show me the benchmark methodology, not just the score &mdash; scores can be gamed.&quot;", readTime: '~10 min', prereqs: [{id:'G5',title:'Emergent Capabilities',slug:'g05-emergence',mod:2},{id:'G14',title:'Pre-Training Data',slug:'g14-pretraining-data',mod:2}], questions: ['What is benchmark contamination and how does it inflate scores?', 'What is Goodhart&#39;s Law and how does it apply to LLM evaluation?', 'How would you design an evaluation for your own agent that resists gaming?'] },
  { module: 7, modTitle: 'Philosophy of Machine Intelligence', id: 'G7', slug: 'g07-grounding', title: 'The Grounding Question', oneLiner: 'Does an LLM understand meaning or manipulate symbols without understanding? The honest answer is somewhere in between, with evidence on both sides.', analogy: 'The Chinese Room &mdash; symbol manipulation at the component level vs. possible understanding at the system level.', why: "Distinguishing &quot;stochastic parrot&quot; from &quot;genuine understanding.&quot; The truth is a defensible middle ground.", argue: "After this page, you can hold the sophisticated middle position: &quot;It&#39;s not a parrot and it&#39;s not human understanding &mdash; it&#39;s something new, with measurable evidence on both sides.&quot;", readTime: '~15 min', prereqs: [{id:'G1',title:'What Weights Actually Encode',slug:'g01-weights',mod:1},{id:'G5',title:'Emergent Capabilities',slug:'g05-emergence',mod:2},{id:'G26',title:'Mechanistic Interpretability',slug:'g26-mechanistic-interpretability',mod:6}], questions: ['What does &quot;grounding&quot; mean in the context of language understanding?', 'What is the &quot;stochastic parrot&quot; argument and what evidence supports/refutes it?', 'Can you articulate a position on LLM understanding you could defend in a debate?'] },
  { module: 7, modTitle: 'Philosophy of Machine Intelligence', id: 'G10', slug: 'g10-intelligence-consciousness', title: 'Intelligence vs. Consciousness', oneLiner: 'Intelligence (goal-directed problem-solving) and consciousness (subjective experience) are separate &mdash; LLMs clearly have the former, almost certainly lack the latter.', analogy: 'A chess engine beating a world champion: clearly intelligent, clearly not conscious. Separable properties.', why: "Settles the core anxiety: yes, it&#39;s measurably intelligent, but that does not imply sentience.", argue: "After this page, you can resolve the deepest confusion: &quot;Intelligence and consciousness are different things. The chess engine is intelligent. That doesn&#39;t make it sentient.&quot;", readTime: '~12 min', prereqs: [{id:'G7',title:'The Grounding Question',slug:'g07-grounding',mod:7}], questions: ['Define intelligence and consciousness as distinct concepts.', 'What evidence would you need to conclude an LLM is conscious?', 'Why does this distinction matter for how you build and deploy agents?'] },
  { module: 7, modTitle: 'Philosophy of Machine Intelligence', id: 'G30', slug: 'g30-functionalism', title: 'Functionalism', oneLiner: "Functionalism holds that mental states are defined by functional roles, not physical substrate &mdash; if true, silicon can think as well as carbon.", analogy: 'A calculator app does the same math as a physical calculator &mdash; the function is identical, the substrate is irrelevant.', why: "Addresses the deepest objection: &quot;it&#39;s just silicon.&quot; If function matters, not material, substrate is irrelevant to intelligence.", argue: "After this page, you can counter the substrate objection: &quot;If the function is identical, the material doesn&#39;t matter &mdash; that&#39;s functionalism, and it&#39;s the dominant position in philosophy of mind.&quot;", readTime: '~10 min', prereqs: [{id:'G10',title:'Intelligence vs. Consciousness',slug:'g10-intelligence-consciousness',mod:7},{id:'G7',title:'The Grounding Question',slug:'g07-grounding',mod:7}], questions: ['What is functionalism and how does it differ from biological naturalism?', 'Why is substrate independence important for evaluating LLM intelligence?', 'What is the strongest argument against functionalism?'] },
  { module: 7, modTitle: 'Philosophy of Machine Intelligence', id: 'G31', slug: 'g31-intentionality', title: 'Intentionality &amp; Aboutness', oneLiner: "When an LLM writes &quot;the cat is on the mat,&quot; is its internal state about a cat, or a pattern that merely resembles aboutness?", analogy: "When a thermostat &quot;senses&quot; temperature, is it about the temperature the way your cold sensation is? The question of genuine aboutness.", why: "The sharpest philosophical question. Engaging with it moves the learner from &quot;is it intelligent?&quot; to &quot;what kind of intelligence is it?&quot;", argue: "After this page, you&#39;ve graduated from &quot;is it intelligent?&quot; to the real question: &quot;What kind of intelligence is it?&quot; &mdash; and you can engage with the sharpest philosophical arguments.", readTime: '~10 min', prereqs: [{id:'G7',title:'The Grounding Question',slug:'g07-grounding',mod:7},{id:'G30',title:'Functionalism',slug:'g30-functionalism',mod:7}], questions: ['What is intentionality in philosophy of mind?', 'How does Searle&#39;s Chinese Room argument challenge LLM intentionality?', 'What would constitute evidence that an LLM&#39;s internal states are genuinely &quot;about&quot; something?'] },
  { module: 7, modTitle: 'Philosophy of Machine Intelligence', id: 'G32', slug: 'g32-frontier', title: 'The Current Frontier', oneLiner: 'Open questions: will scaling continue producing new capabilities, can LLMs develop genuine world models, will alignment scale with capability, what are transformer limits?', analogy: "The map at the edge of explored territory: here be dragons, here be opportunity, and honestly &mdash; we don&#39;t yet know.", why: "The capstone. The learner can now articulate what is known, debated, and unknown &mdash; holding uncertainty without defaulting to dismissal or hype.", argue: "After completing this course, you can give the 60-second answer to &quot;are LLMs just guessers?&quot; &mdash; grounded in evidence, honest about limits, and intellectually defensible.", readTime: '~15 min', prereqs: [{id:'G7',title:'The Grounding Question',slug:'g07-grounding',mod:7},{id:'G28',title:'Benchmarking Intelligence',slug:'g28-benchmarking',mod:6},{id:'G25',title:'The Autonomy Spectrum',slug:'g25-autonomy-spectrum',mod:5}], questions: ['Name two open questions about LLM intelligence the field has not answered.', 'What is the strongest argument scaling will continue? That it won&#39;t?', 'What would you tell someone who says &quot;LLMs are just supercharged next-word guessers&quot; &mdash; in 60 seconds?'] }
];

let count = 0;
let skipped = 0;
for (const g of gaps) {
  const dir = path.join(base, `module-${g.module}`);
  const file = path.join(dir, `${g.slug}.html`);

  let prereqSection;
  if (g.prereqs.length > 0) {
    const chips = g.prereqs.map(p =>
      `    <a href="../module-${p.mod}/${p.slug}.html" class="prereq-chip">${p.id} &mdash; ${p.title}</a>`
    ).join('\n');
    prereqSection = `  <div class="prereqs">\n    <span class="prereqs-label">Prerequisites:</span>\n${chips}\n  </div>`;
  } else {
    prereqSection = `  <div class="prereqs">\n    <span class="prereqs-label">Prerequisites:</span>\n    <span style="font-size:0.78rem;color:var(--text-dim);">None &mdash; entry point</span>\n  </div>`;
  }

  const questionsHtml = g.questions.map(q => `        <li>${q}</li>`).join('\n');

  const firstGapSlug = gaps.find(x => x.module === g.module).slug;

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${g.id} &mdash; ${g.title} &mdash; LLM Intelligence</title>
<link rel="stylesheet" href="../css/style.css">
<meta property="og:title" content="${g.id} &mdash; ${g.title}">
<meta property="og:description" content="${g.oneLiner}">
<meta property="og:type" content="article">
<link rel="icon" href="../img/favicon.svg" type="image/svg+xml">
</head>
<body>

<a href="#main" class="skip-link">Skip to content</a>
<div class="scroll-progress"></div>

<button class="mobile-nav-toggle" aria-label="Open navigation">&#9776;</button>
<div class="overlay"></div>

<nav id="sidebar" aria-label="Course navigation"></nav>

<main id="main">

  <div class="breadcrumb">
    <a href="../index.html">Home</a>
    <span class="sep">&#8250;</span>
    <a href="../module-${g.module}/${firstGapSlug}.html">Module ${g.module}: ${g.modTitle}</a>
    <span class="sep">&#8250;</span>
    ${g.title}
  </div>

  <div class="hero">
    <div class="gap-badge" data-module="${g.module}">${g.id} &middot; Module ${g.module}</div>
    <h1>${g.title}</h1>
    <p class="one-liner">${g.oneLiner}</p>
    <span class="reading-time">${g.readTime}</span>
    <div class="analogy">
      <div class="analogy-label">Anchor Analogy</div>
      ${g.analogy}
    </div>
  </div>

  <div class="callout callout-why">
    <div class="callout-label">Why This Matters</div>
    ${g.why}
  </div>

  <div class="callout callout-argue">
    <div class="callout-label">After This Page, You Can Argue</div>
    ${g.argue}
  </div>

${prereqSection}

  <div class="content">

    <div class="content-placeholder">
      <strong>Content Coming Soon</strong>
      This concept page is scaffolded and ready for content. The full explanation, interactive elements, and citations will be added in the content-writing phase.
    </div>
  </div>

  <div class="verification" role="region" aria-label="Verification questions">
    <div class="verification-header" role="button" aria-expanded="false" tabindex="0">
      <h3>Verification Questions</h3>
      <span class="toggle-icon" aria-hidden="true">&#9660;</span>
    </div>
    <div class="verification-body">
      <ol>
${questionsHtml}
      </ol>
    </div>
  </div>

  <div class="page-nav"></div>

</main>

<script src="../js/nav.js"></script>
<script>LLMNav.init('${g.slug}');</script>
</body>
</html>`;

  // --- Non-destructive guard (Phase 0) ---------------------------------------
  // A pristine scaffold contains "content-placeholder"; an authored page does not.
  // Never clobber an authored page unless --force, and even then back it up first.
  if (fs.existsSync(file)) {
    const existing = fs.readFileSync(file, 'utf8');
    if (!existing.includes('content-placeholder')) {
      if (!FORCE) {
        console.warn('SKIP (has hand-written content): ' + file);
        skipped++;
        continue;
      }
      const bak = `${file}.${Date.now()}.bak`;
      fs.writeFileSync(bak, existing, 'utf8');
      console.warn('FORCED overwrite — backup: ' + bak + ' (re-merge your content div!)');
    }
  }

  fs.writeFileSync(file, html, 'utf8');
  count++;
}

console.log('Wrote ' + count + ' page(s)' + (skipped ? ', skipped ' + skipped + ' with hand-written content' : '') + '.');
